AWSTemplateFormatVersion: '2010-09-09'
Description: Shows how to set up a new github based project

Parameters:
  RepoName:
    Type: String
    Description: |
      The name of the repo that is being created and configured
    Default: MyRepo
    
Resources:
  Membership:
    Type: GitHub::Organizations::Membership
    Properties:
      Organization: ACME-CloudFormation
      Username: ACME-cloudformation-test-user
      Role: member
  MyRepo:
    Type: GitHub::Repositories::Repository
    Properties:
      Org: ACME-CloudFormation
      Name: !Ref RepoName
      Description: Repo created by cloudformation example
      Homepage: https://GitHub.com
      Private: true
      Visibility: private
      HasIssues: true
      HasProjects: false
      HasWiki: true
      IsTemplate: false
      AutoInit: true
      GitIgnoreTemplate: Node
      LicenseTemplate: mit
      AllowSquashMerge: true
      AllowMergeCommit: true
      AllowRebaseMerge: true
      AllowAutoMerge: true
      DeleteBranchOnMerge: false
      Archived: false
  MyWebHook:
    Type: GitHub::Repositories::Webhook
    DependsOn: MyRepo
    Properties:
      Url: http://some.url.com
      Owner: ACME-CloudFormation
      Name: web
      Active: false
      Events:
        - push
      Repository: !Ref RepoName
  ExternalCollaborator:
    Type: GitHub::Repositories::Collaborator
    DependsOn: MyRepo
    Properties:
      Owner: ACME-CloudFormation
      Repository: !Ref RepoName
      Username: alasdairhodge
      Permission: pull
  DemoTeam:
    Type: GitHub::Teams::Team
    Properties:
      Name: My Demo Team
      Organization: ACME-CloudFormation
      Description: My new Team
      Privacy: secret
  DemoTeamMemberMe:
    Type: GitHub::Teams::Membership
    Properties:
      Org: ACME-CloudFormation
      TeamSlug: !GetAtt DemoTeam.Slug
      Username: organisation-member
      Role: member
  DemoTeamAccessRepo:
    Type: GitHub::Teams::RepositoryAccess
    DependsOn: MyRepo
    Properties:
      Org: ACME-CloudFormation
      Team: !GetAtt DemoTeam.Slug
      Owner: ACME-CloudFormation
      Repository: !Ref RepoName
      Permission: pull


